import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <img
        src="http://cucsa.org.uk/wp-content/uploads/2015/10/Work_In_Progress.png"
        alt="Working on it!"
      />
    </div>
  );
};

export default Home;
