export const personSchema = {
  "@context": "http://www.schema.org",
  "@type": "Person",
  name: "Nicolas Andres Castro Malinarich",
  jobTitle: "Developer",
  url: "https://www.nicolasmalinarich.cl/",
  address: {
    "@type": "PostalAddress",
    streetAddress: "avenida manuel antonio matta #0562",
    addressLocality: "Quilicura",
    addressRegion: "Region metropolitana",
    postalCode: "8730286",
    addressCountry: "Chile",
  },
  email: "nicolas.malinarich@hotmail.com",
  telephone: "+56968300885",
  birthDate: "1997-05-10",
  sameAs: [
    "https://www.facebook.com/nicolas.malinarich",
    "https://www.instagram.com/_malinarich_/",
    "https://www.linkedin.com/in/nicolas-malinarich/",
    "https://www.nicolasmalinarich.cl/",
    "https://github.com/Malinarich1",
  ],
};
